apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaspnetapp
  labels:
    app: myaspnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: myaspnetapp
  template:
    metadata:
      labels:
        app: myaspnetapp
        service: myaspnetapp
    spec:
      containers:
        - name: myaspnetapp
          image: mygab22acr.azurecr.io/myaspnetapp-prod:2280096714
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
     
---
apiVersion: v1
kind: Service
metadata:
  name: myaspnetapp-svc
  labels:
    app: myaspnetapp
    service: myaspnetapp-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: myaspnetapp