apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaspnetapp-stage
  labels:
    app: myaspnetapp-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      service: myaspnetapp-stage-svc
  template:
    metadata:
      labels:
        app: myaspnetapp-stage
        service: myaspnetapp-stage-svc
    spec:
      containers:
        - name: myaspnetapp
          image: mygab22acr.azurecr.io/myaspnetapp-stage:121
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
     
---
apiVersion: v1
kind: Service
metadata:
  name: myaspnetapp-stage-svc
  labels:
    app: myaspnetapp-stage
    service: myaspnetapp-stage-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: myaspnetapp-stage-svc