apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp
  labels:
    app: mynodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
        service: mynodeapp
    spec:
      containers:
        - name: mynodeapp
          image: mygab22acr.azurecr.io/mynodeapp-stage:121
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mynodeapp-svc
  labels:
    app: mynodeapp
    service: mynodeapp-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    service: mynodeapp